import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// fonts
const hind = localFont({
  src: [
    {
      path: "../public/fonts/hind-light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/hind-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/hind-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/hind-semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/hind-bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-hind",
});

const melodrame = localFont({
  src: "../public/fonts/relationship-of-mélodrame.ttf",
  variable: "--font-melodrame",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hind.variable} ${melodrame.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
